project_identifier: 'P2P'
api_key_env: P2P_CROWDIN_API_KEY

files:
  - source: /crowdin/messages.json
    translation: /src/translations/%two_letters_code%.json
    languages_mapping:
      two_letters_code:
        zh-CN: zh_cn
        zh-TW: zh_tw